version: "3"
services:

  main:
    build: .
    volumes:
      - ./scripts:/scripts
    ports:
      - "8089:8089"

  worker:
    build: .
    command: "--main-host=main"
    volumes:
      - ./scripts:/scripts
